// src/scheduleData.js

const scheduleData = {
  Monday: [
    {
      time: "6:00 am - 7:00 am",
      task: "Reading Book",
      goal: "Mindfulness",
      notes: "",
      date: "",
    },
    {
      time: "7:15 am - 9:15 am",
      task: "Studying Course (Pomodoro)",
      goal: "Career and Dreams",
      notes: "",
      date: "",
    },
    {
      time: "9:30 am - 11:00 am",
      task: "Project/Assignment Work",
      goal: "Practice",
      notes: "",
      date: "",
    },
    {
      time: "11:30 am - 5:00 pm",
      task: "Full-Time Job (Deep Work Session)",
      goal: "Job",
      notes: "",
      date: "",
    },
    {
      time: "5:00 pm - 7:00 pm",
      task: "Household Tasks and Family Time",
      goal: "",
      notes: "",
      date: "",
    },
    { time: "7:00 pm - 8:00 pm", task: "Rest", goal: "", notes: "", date: "" },
    {
      time: "8:00 pm - 11:00 pm",
      task: "Project/Course Work (Pomodoro)",
      goal: "Dreams",
      notes: "",
      date: "",
    },
  ],
  Tuesday: [
    {
      time: "6:00 am - 7:00 am",
      task: "Reading Book",
      goal: "Mindfulness",
      notes: "",
      date: "",
    },
    {
      time: "7:15 am - 11:00 am",
      task: "PailSail (Pomodoro)",
      goal: "Dreams",
      notes: "",
      date: "",
    },
    {
      time: "8:00 pm - 11:00 pm",
      task: "Project/Course Work (Pomodoro)",
      goal: "Dreams",
      notes: "",
      date: "",
    },
  ],
  Wednesday: [
    {
      time: "6:00 am - 7:00 am",
      task: "Reading Book",
      goal: "Mindfulness",
      notes: "",
      date: "",
    },
    {
      time: "7:15 am - 9:15 am",
      task: "Studying Course (Pomodoro)",
      goal: "Career and Dreams",
      notes: "",
      date: "",
    },
    {
      time: "9:30 am - 11:00 am",
      task: "Project/Assignment Work",
      goal: "Practice",
      notes: "",
      date: "",
    },
    {
      time: "11:30 am - 5:00 pm",
      task: "Full-Time Job (Deep Work Session)",
      goal: "Job",
      notes: "",
      date: "",
    },
    {
      time: "5:00 pm - 7:00 pm",
      task: "Household Tasks and Family Time",
      goal: "",
      notes: "",
      date: "",
    },
    { time: "7:00 pm - 8:00 pm", task: "Rest", goal: "", notes: "", date: "" },
    {
      time: "8:00 pm - 11:00 pm",
      task: "Project/Course Work (Pomodoro)",
      goal: "Dreams",
      notes: "",
      date: "",
    },
  ],
  Thursday: [
    {
      time: "6:00 am - 7:00 am",
      task: "Reading Book",
      goal: "Mindfulness",
      notes: "",
      date: "",
    },
    {
      time: "7:15 am - 11:00 am",
      task: "PailSail (Pomodoro)",
      goal: "Dreams",
      notes: "",
      date: "",
    },
    {
      time: "8:00 pm - 11:00 pm",
      task: "Project/Course Work (Pomodoro)",
      goal: "Dreams",
      notes: "",
      date: "",
    },
  ],
  Friday: [
    {
      time: "6:00 am - 7:00 am",
      task: "Reading Book",
      goal: "Mindfulness",
      notes: "",
      date: "",
    },
    {
      time: "7:15 am - 9:15 am",
      task: "Studying Course (Pomodoro)",
      goal: "Career and Dreams",
      notes: "",
      date: "",
    },
    {
      time: "9:30 am - 11:00 am",
      task: "Project/Assignment Work",
      goal: "Practice",
      notes: "",
      date: "",
    },
    {
      time: "11:30 am - 5:00 pm",
      task: "Full-Time Job (Deep Work Session)",
      goal: "Job",
      notes: "",
      date: "",
    },
    {
      time: "5:00 pm - 7:00 pm",
      task: "Household Tasks and Family Time",
      goal: "",
      notes: "",
      date: "",
    },
    { time: "7:00 pm - 8:00 pm", task: "Rest", goal: "", notes: "", date: "" },
    {
      time: "8:00 pm - 11:00 pm",
      task: "Project/Course Work (Pomodoro)",
      goal: "Dreams",
      notes: "",
      date: "",
    },
  ],
  Saturday: [
    {
      time: "6:00 am - 7:00 am",
      task: "Reading Book",
      goal: "Mindfulness",
      notes: "",
      date: "",
    },
    {
      time: "7:15 pm - 10:00 pm",
      task: "Cutting Grass, Plants and Garage",
      goal: "",
      notes: "",
      date: "",
    },
    { time: "12 am - 4:00 pm", task: "Grocery", goal: "", notes: "", date: "" },
    {
      time: "5:15 pm - 8:00 pm",
      task: "Back yard and Front yard work, Home Improvement",
      goal: "",
      notes: "",
      date: "",
    },
  ],
  Sunday: [
    {
      time: "6:00 am - 7:00 am",
      task: "Reading Book",
      goal: "Mindfulness",
      notes: "",
      date: "",
    },
    {
      time: "7:15 am - 9:15 am",
      task: "Studying Course (Pomodoro)",
      goal: "Career and Dreams",
      notes: "",
      date: "",
    },
    {
      time: "9:30 am - 11:00 am",
      task: "Project/Assignment Work",
      goal: "Practice",
      notes: "",
      date: "",
    },
    {
      time: "11:30 am - 5:00 pm",
      task: "Business Development (Deep Work Session)",
      goal: "Job",
      notes: "",
      date: "",
    },
    {
      time: "5:00 pm - 7:00 pm",
      task: "Household Tasks and Family Time",
      goal: "",
      notes: "",
      date: "",
    },
    { time: "7:00 pm - 8:00 pm", task: "Rest", goal: "", notes: "", date: "" },
    {
      time: "8:00 pm - 11:00 pm",
      task: "Project/Course Work (Pomodoro)",
      goal: "Dreams",
      notes: "",
      date: "",
    },
  ],
};

export default scheduleData;
